### PR TITLE
Update runtime to GNOME 41

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update libwmf
- Update exiv2
- Add patch for geeqie

Closes #10 
Closes #11

### CODE REVIEW

**Comment by hfiguiere** [comment]
I still have question as to why this is not built with Gtk3....

**Comment by hfiguiere** [comment]
> I still have question as to why this is not built with Gtk3....

Nevermind I see #4.

**Comment by Hofer-Julian** [comment]
@hfiguiere Thanks for working on this.
I currently cannot test this, but if you tested that everything works fine we can merge it from my side.

**Comment by Hofer-Julian** [comment]
Works like a charm, thanks @hfiguiere﻿

**Pull request merged**
