### PR TITLE
Move to gtk2

### PR DESCRIPTION
**Pull request by Hofer-Julian**
This is done, because GTK3 is quite buggy.
GTK3 is marked experimental by the developers (see http://www.geeqie.org/installing.html).

### CODE REVIEW

**Comment by paperdigits** [comment]
Were you hitting some bugs? I used the gtk3 for a while and never ran into any any problems.

**Comment by Hofer-Julian** [comment]
Yes, e.g. the sidebar doesn't maintain its position after closing and reopeing geeqie. One of the Geeqie developers mentioned, that problems like this will hopefully disappear with GTK4

**Comment by Hofer-Julian** [comment]
> > Yes, e.g. the sidebar doesn't maintain its position after closing and reopeing geeqie. One of the Geeqie developers mentioned, that problems like this will hopefully disappear with GTK4
> 
> I guess that was me - but I cannot now find a reference to that discussion. I no longer see that problem. Are there any other problems preventing Geeqie with GTK3 being a flatpak?

Not to my knowledge :)

**Comment by yourealwaysbe** [comment]
> > Yes, e.g. the sidebar doesn't maintain its position after closing and reopeing geeqie. One of the Geeqie developers mentioned, that problems like this will hopefully disappear with GTK4
> I guess that was me - but I cannot now find a reference to that discussion.

What does it mean that the sidebar doesn't maintain position? I'm playing with an updated flatpak build at the moment.

**Comment by Hofer-Julian** [comment]
For example, you resize the sidebar, close the app, start it again and the sidebar is not at the position to which you resized it to.

**Pull request merged**
